services:
  mysql:
    image: mysql:8.4
    container_name: site-fred-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_fred
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp"]
      interval: 5s
      timeout: 3s
      retries: 30
volumes:
  mysql_data: